#page title
title                                : Graphaello                                                                                     # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

icon                                  : /assets/logo.png
description                           : A Tool for Writing Declarative, Type-Safe and Data-Driven Applications in SwiftUI using GraphQL.

enable_smart_app_banner                   : true

paper_link : http://quintero.io/master-thesis/thesis.pdf

your_name                                 : Mathias Quintero                              
your_link                                 : https://quintero.io                     
your_city                                 : Munich      
twitter_username                          : nerdsupremacist
github_username                           : nerdsupremacist

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Loading and Error State Handling 
    description                           : You will never have to write UI for loading or error states ever again. Just focus on what your App looks like when the data is there. We will take care of the rest.
    fontawesome_icon_name                 : sync
    
  - title                                 : Declarative
    description                           : Don't tell your App how to fetch data. Just declare the data that you need. Graphaello will fetch it for you. 
    fontawesome_icon_name                 : scroll

  - title                                 : Type-Safety
    description                           : Never mix up values again. With compile time safety, you will always know what data you're getting. You can rest assured more mistakes are now caught at compile time.
    fontawesome_icon_name                 : shield-alt

  - title                                 : Reusable Components
    description                           : Do you have UI components that you want to use in multiple places? No problem! Graphaello was built with modularity and reusability in mind. You can use fragments to describe components that you want to reuse. 
    fontawesome_icon_name                 : box-open

  - title                                 : Paging Support
    description                           : Do you need to show a lot of data. Graphaello supports Paging via connections. You can control every aspect of pagination or use the built-in infinite scrolling.
    fontawesome_icon_name                 : stream
  
  - title                                 : Only write Swift
    description                           : You never actually have to write any GraphQL queries. Your UI Code *IS* your GraphQL code. You no longer have to go back and forth between files. If you need data, simply ask for it in your UI.
    fontawesome_icon_name                 : swift
    use_fab                               : true


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#ffffff"

cover_overlay_color                       : "#3A4045"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


links:
  - name: GitHub
    url: https://github.com/nerdsupremacist/Graphaello
    include_in_header: true
  - name: GraphQL
    url: https://graphql.org
    include_in_header: false
  - name: GraphZahl
    url: https://github.com/nerdsupremacist/GraphZahl
    include_in_header: false







####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true