on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Upload Binaries
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: latest
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Create Release Folder
        run: mkdir release
      - name: Build Artifacts
        run: make install prefix=./release
      - name: Archive Artifacts
        run: tar -cf release.tar.gz release/*
      - name: Get Release ID
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/zip
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: graphaello
          homebrew-tap: nerdsupremacist/homebrew-graphaello
          base-branch: master
          download-url: https://github.com/nerdsupremacist/Graphaello/releases/download/${{ steps.tag.outputs.result }}/release.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }} 
