on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Upload Binaries
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: latest
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Create Release Folder
        run: mkdir release
      - name: Build Artifacts
        run: make install prefix=./release
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'release/*'
